export const FORMAT_CATALOG = [
  {
    code: 'PREOP_BENEFICIO',
    name: 'Preoperativo de Planta Beneficio',
    documentCode: 'SAI-CAL-F015',
    sheetCount: 8,
    sortOrder: 1,
    noSunday: true,
    sheets: [
      { sheetOrder: 1, name: 'Zona Sangría', slug: 'zona-sangria' },
      { sheetOrder: 2, name: 'Zona Intermedia', slug: 'zona-intermedia' },
      { sheetOrder: 3, name: 'Zona Limpia', slug: 'zona-limpia' },
      { sheetOrder: 4, name: 'Subproductos (Pág. 4)', slug: 'sub-p-4' },
      { sheetOrder: 5, name: 'Subproductos (Pág. 5)', slug: 'sub-5' },
      { sheetOrder: 6, name: 'Subproductos (Pág. 6)', slug: 'sub-p-6' },
      { sheetOrder: 7, name: 'Refrigeración', slug: 'refrigeracion' },
      { sheetOrder: 8, name: 'Cavas', slug: 'cavas' },
    ],
  },
  {
    code: 'PREOP_DESPOSTE',
    name: 'Preoperativo de Planta Desposte',
    documentCode: 'AC-FR-017',
    sheetCount: 4,
    sortOrder: 2,
    noSunday: true,
    sheets: [
      { sheetOrder: 1, name: 'Preoperativo 1', slug: 'preoperativo-1' },
      { sheetOrder: 2, name: 'Preoperativo 2', slug: 'preoperativo-2' },
      { sheetOrder: 3, name: 'Preoperativo 3', slug: 'preoperativo-3' },
      { sheetOrder: 4, name: 'Preoperativo 4', slug: 'preoperativo-4' },
    ],
  },
  {
    code: 'DESPACHO_PRODUCTO',
    name: 'Despacho de Producto Terminado',
    documentCode: 'AC-FR-015',
    sheetCount: 1,
    sortOrder: 3,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Despachos', slug: 'despachos' }],
  },
  {
    code: 'PROCESO_DESPOSTE',
    name: 'Verificación Desposte Operativo',
    documentCode: 'AC-FR-014',
    sheetCount: 5,
    sortOrder: 4,
    noSunday: true,
    sheets: [
      { sheetOrder: 1, name: 'Diario 1', slug: 'diario-1' },
      { sheetOrder: 2, name: 'Diario 2', slug: 'diario-2' },
      { sheetOrder: 3, name: 'Diario 3', slug: 'diario-3' },
      { sheetOrder: 4, name: 'Diario 4', slug: 'diario-4' },
      { sheetOrder: 5, name: 'Diario 5', slug: 'diario-5' },
    ],
  },
  {
    code: 'RECEPCION_CANALES_FORANEAS',
    name: 'Recepción e Inspección de Canales Foráneas',
    documentCode: 'AC-FR-016',
    sheetCount: 1,
    sortOrder: 5,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Recepción Foráneas', slug: 'principal' }],
  },
  {
    code: 'RECEPCION_CANALES_DESPOSTE',
    name: 'Recepción e Inspección de Canales para Desposte',
    documentCode: 'AC-FR-011',
    sheetCount: 1,
    sortOrder: 6,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Recepción Canales', slug: 'principal' }],
  },
  {
    code: 'VERIFICACION_PRODUCTO',
    name: 'Verificación de Producto Terminado',
    documentCode: 'AC-FR-022',
    sheetCount: 2,
    sortOrder: 7,
    noSunday: true,
    sheets: [
      { sheetOrder: 1, name: 'Producto Refrigerado', slug: 'refrigerado' },
      { sheetOrder: 2, name: 'Producto Congelado', slug: 'congelado' },
    ],
  },
  {
    code: 'INSPECCION_VEHICULOS',
    name: 'Inspección de Vehículos',
    documentCode: 'AC-FR-009',
    sheetCount: 1,
    sortOrder: 8,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Inspección', slug: 'principal' }],
  },
  {
    code: 'CALIBRACION_PH',
    name: 'Calibración pH-metro',
    documentCode: 'AC-FR-006',
    sheetCount: 1,
    sortOrder: 9,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Calibración', slug: 'principal' }],
  },
  {
    code: 'HABITOS_HIGIENICOS',
    name: 'Inspección de Hábitos Higiénicos',
    documentCode: 'AC-FR-007',
    sheetCount: 1,
    sortOrder: 10,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Inspección', slug: 'principal' }],
  },
  {
    code: 'DEVOLUCIONES',
    name: 'Seguimiento a Devoluciones',
    documentCode: 'AC-FR-018',
    sheetCount: 1,
    sortOrder: 11,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Devoluciones', slug: 'principal' }],
  },
  {
    code: 'DECOMISOS',
    name: 'Formato de Decomisos',
    documentCode: 'AC-FR-010',
    sheetCount: 1,
    sortOrder: 12,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Decomisos', slug: 'principal' }],
  },
  {
    code: 'LINEA_OPERATIVO',
    name: 'Verificación Línea Operativo',
    documentCode: 'AC-FR-00',
    sheetCount: 1,
    sortOrder: 13,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Línea Operativo', slug: 'principal' }],
  },
  {
    code: 'PC_COMESTIBLE_OPERATIVO',
    name: 'Verificación PC Comestibles Operativo',
    documentCode: 'SAI-CAL-F010',
    sheetCount: 4,
    sortOrder: 14,
    noSunday: true,
    sheets: [
      { sheetOrder: 1, name: 'Área Cabezas', slug: 'cabezas' },
      { sheetOrder: 2, name: 'Patas y Manos', slug: 'patas-manos' },
      { sheetOrder: 3, name: 'Vísceras Blancas', slug: 'visceras-blancas' },
      { sheetOrder: 4, name: 'Vísceras Rojas', slug: 'visceras-rojas' },
    ],
  },
  {
    code: 'POES_OPERATIVO',
    name: 'Verificación POES Operativo',
    documentCode: 'AC-FR-00',
    sheetCount: 1,
    sortOrder: 15,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'POES Operativo', slug: 'principal' }],
  },
  {
    code: 'PC_COMESTIBLES_INOCUIDAD',
    name: 'Verificación de Productos Cárnicos Comestibles',
    documentCode: 'AC-FR-00',
    sheetCount: 1,
    sortOrder: 16,
    noSunday: true,
    sheets: [{ sheetOrder: 1, name: 'Verificación PC', slug: 'principal' }],
  },
] as const;

export type FormatCode = (typeof FORMAT_CATALOG)[number]['code'];
